require('plugins')
require('keymappings')
require('settings')
require('globals')
require('nvimtree')
require('colorscheme')
require('barbar')
require('nvim-telescope')
require('nvim-presence')
require('nvim-bujo')
require('autopairs')
require('comment')

-- LSP
require('lsp')
